apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc
  labels:
    app: dc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dc
  template:
    metadata:
      labels:
        app: dc
    spec:
      containers:
      - name: dc-app
        image: sarveshmore/dc:latest
        ports:
        - containerPort: 80
